### ISSUE TITLE
Tutorial and example app

### ISSUE THREAD

**Issue by justbennet** [BIDS-Apps/example#14]
Not sure what is wrong, so the question may be semi-coherent.

I am trying to work through the tutorial at http://bids-apps.neuroimaging.io/tutorial/

I have Docker version 1.10.3, build d381c64-unsupported as installed by yum on CentOS 7.

Our Docker is currently locked down so only root can talk to the daemon, so I have to

```
$ sudo docker run -i --rm \
    -v /tmp/bids/ds005_R1.1.0:/bids_dataset:ro \
    -v /tmp/bids/ds005_R1.1.0/output:/outputs \
    bids:example \
    /bids_dataset /outputs participant --participant_label 01
```

using the ds005 data set downloaded from the example files today.  It runs

`bet /bids_dataset/sub-01/anat/sub-01_T1w.nii.gz /outputs/sub-01_brain.nii.gz`

and produces

```
$ ls -l ds005_R1.1.0/output/
total 1216
-rw-r--r-- 1 root root 1242149 Sep  4 15:47 sub-01_brain.nii.gz
```

I then try to convert the docker image to a Singularity image (this is on a machine in the cluster) using

```
sudo docker run --privileged -ti --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/singularity:/output docker2singularity \
    bids:example
```

after first grabbing the filos/docker2singularity Docker bundle and building a local version, setting the Docker version to match ours.  That seems to go OK, and produces

```
$ sudo docker run --privileged -ti --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/singularity:/output docker2singularity \
    bids:example

Size: 1615 MB for the singularity container
Creating a sparse image with a maximum size of 1615MiB...
Using given image size of 1615
Formatting image (/sbin/mkfs.ext3)
Done. Image can be found at: /output/bids_example-2016-09-04-a2e66f1e787d.img

Singularity: sexec (U=0,P=144)> Command=exec, Container=/output/bids_example-2016-09-04-a2e66f1e787d.img, CWD=/, Arg1=/bin/sh
Fixing permissions.
Singularity: sexec (U=0,P=150)> Command=exec, Container=/output/bids_example-2016-09-04-a2e66f1e787d.img, CWD=/, Arg1=/bin/sh
Singularity: sexec (U=0,P=179)> Command=exec, Container=/output/bids_example-2016-09-04-a2e66f1e787d.img, CWD=/, Arg1=/bin/sh
Adding mount points
Singularity: sexec (U=0,P=8600)> Command=exec, Container=/output/bids_example-2016-09-04-a2e66f1e787d.img, CWD=/, Arg1=/bin/sh
Stopping container, please wait.
a2e66f1e787d
```

However, no combination that I can find produces a run of `bet`.  When running from Docker, the path mapping from the host machine to the container has to be specified on the command line.  I am not seeing anything that looks like that in the conversion to singularity or in the singularity invocation.  My suspicion is that it's failing because no files are found because `/bids_dataset` and `/output` are not getting properly mapped.

Have I done something wrong?  Are the tutorial instructions incomplete?

How do we tell the Singularity application where the data and output files are?

Sorry if this is the wrong place to post; I don't see a place to post for text in the tutorial.

**Comment by chrisgorgo** [comment]
"However, no combination that I can find produces a run of bet."
Could you elaborate? How are you trying to run the singularity image? What
are the results?

**Comment by justbennet** [comment]
Whoops, sorry.  Bad copy and paste management.

After I produce the Singularity image using the commands above, and moving the singularity image to the folder that contains `d006_R1.1.0`, I try, per the Tutorial page, this

```
./bids_example-2016-09-04-a2e66f1e787d.img \
    /bids_dataset \
    /outputs participant \
    --participant_label 01
```

No error is generated, but neither is an output.

**Comment by chrisgorgo** [comment]
Does /bids_dataset folder exists on the host file system and is a root of a
BIDS dataset? Is the installation of singularity on your host configured to
access any folder (I doubt it, most are limited to /scratch and $HOME).

I pushed a version of the example app with a validator built in. This
should give better debug info.

**Comment by justbennet** [comment]
I created `/bids_dataset` and `/outputs`, where

```
$ ls /bids_dataset
CHANGES                   README  sub-04  sub-08  sub-12  sub-16
dataset_description.json  sub-01  sub-05  sub-09  sub-13  task-mixedgamblestask_bold.json
output                    sub-02  sub-06  sub-10  sub-14
participants.tsv          sub-03  sub-07  sub-11  sub-15
```

Running

```
sudo /tmp/singularity/bids_example-2016-09-04-a2e66f1e787d.img /bids_dataset /outputs participant --participant_label 01
```

still does not result in any output.

I can rebuild things tomorrow, and hopefully the additional diagnostics in the new `bids-example` will shed light on this.

**Comment by chrisgorgo** [comment]
It's most likely something with your singularity install. Try moving the
bids director somewhere inside your $HOME and try again.

**Comment by justbennet** [comment]
The singularity installation is from EPEL via yum.

OK.  That seems to have maybe fixed the filesystem.  Now I have to go back
an remake the Docker image, as something seems to have gone wrong there:

$ /tmp/singularity/bids_example-2016-09-04-aecc9aa048f3.img
/home/bennet/bids_dataset/d005_R1.1.0 /tmp/bids_output participant
--participant_label 01
bet /home/bennet/bids_dataset/d005_R1.1.0/sub-01/anat/sub-01_T1w.nii.gz
/tmp/bids_output/sub-01_brain.nii.gz
/bin/sh: 1: bet: not found

Traceback (most recent call last):
  File "/run.py", line 69, in <module>
    run(cmd)
  File "/run.py", line 25, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 127

Enough for one day.  Thanks for all your help!

-- bennet

**Comment by chrisgorgo** [comment]
I could not replicate this. Are you sure the conversion process run without
issue?

**Comment by justbennet** [comment]
Chris,

I unistalled docker from my machine this morning, removed the entire contents of `/var/lib/docker`, reinstalled docker, and recreated the example container.  It runs without error.

```
$ sudo docker run -ti --rm \
>       -v /tmp/data/ds005_R1.1.0:/bids_dataset:ro \
>       -v /tmp/bids_output:/outputs \
>       example \
>       /bids_dataset /outputs participant --participant_label 01

    1: You should define 'SliceTiming' for this file. If you don't provide this information slice time correction will not be possible. (code: 13)
        /sub-01/func/sub-01_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-01/func/sub-01_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-01/func/sub-01_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-04/func/sub-04_task-mixedgamblestask_run-01_bold.nii.gz
        ... and 38 more files having this issue (Use --verbose to see them all).

        Summary:                 Available Tasks:          Available Modalities: 
        133 Files, 1.77GB        mixed-gambles task        T1w                   
        16 - Subjects                                      inplaneT2             
        1 - Session                                        bold                  


bet /bids_dataset/sub-01/anat/sub-01_T1w.nii.gz /outputs/sub-01_brain.nii.gz
```

Then I run the following command to create the Singularity image.

```
$ sudo docker run --privileged -ti --rm  \
>       -v /var/run/docker.sock:/var/run/docker.sock \
>       -v /tmp/singularity:/output \
>       filo/docker2singularity \
>       example
Unable to find image 'filo/docker2singularity:latest' locally
latest: Pulling from filo/docker2singularity
e110a4a17941: Pull complete 
49e2842bdfdf: Pull complete 
a2e2c7c833a0: Pull complete 
62fa1d70dc3a: Pull complete 
6628c5827b01: Pull complete 
d2ec67765253: Pull complete 
cc4821134dcf: Pull complete 
c4dcf3de58df: Pull complete 
11f6e4a02f2b: Pull complete 
Digest: sha256:aa5f93023afda10d9e18a88c7a088b7be2228346968ada8919663361a93760ca
Status: Downloaded newer image for filo/docker2singularity:latest
Size: 1615 MB for the singularity container
Creating a sparse image with a maximum size of 1615MiB...
Using given image size of 1615
Formatting image (/sbin/mkfs.ext3)
Done. Image can be found at: /output/example-2016-09-05-6b9e3812277d.img
Singularity: sexec (U=0,P=145)> Command=exec, Container=/output/example-2016-09-05-6b9e3812277d.img, CWD=/, Arg1=/bin/sh
Fixing permissions.
Singularity: sexec (U=0,P=151)> Command=exec, Container=/output/example-2016-09-05-6b9e3812277d.img, CWD=/, Arg1=/bin/sh
Singularity: sexec (U=0,P=180)> Command=exec, Container=/output/example-2016-09-05-6b9e3812277d.img, CWD=/, Arg1=/bin/sh
Adding mount points
Singularity: sexec (U=0,P=8601)> Command=exec, Container=/output/example-2016-09-05-6b9e3812277d.img, CWD=/, Arg1=/bin/sh
Stopping container, please wait.
6b9e3812277d
[bennet@flux-build2 tmp]$ ls /tmp/singularity
example-2016-09-05-6b9e3812277d.img
```

That seems like it is running without issue.  After running that, I run

```
$ /tmp/singularity/example-2016-09-05-6b9e3812277d.img /home/bennet/bids_dataset/d005_R1.1.0 /home/bennet/bids_output participant --participant_label 01
    1: You should define 'SliceTiming' for this file. If you don't provide this information slice time correction will not be possible. (code: 13)
        /sub-01/func/sub-01_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-01/func/sub-01_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-01/func/sub-01_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-04/func/sub-04_task-mixedgamblestask_run-01_bold.nii.gz
        ... and 38 more files having this issue (Use --verbose to see them all).

        Summary:                 Available Tasks:          Available Modalities: 
        133 Files, 1.77GB        mixed-gambles task        T1w                   
        16 - Subjects                                      inplaneT2             
        1 - Session                                        bold                  


bet /home/bennet/bids_dataset/d005_R1.1.0/sub-01/anat/sub-01_T1w.nii.gz /home/bennet/bids_output/sub-01_brain.nii.gz
/bin/sh: 1: bet: not found

Traceback (most recent call last):
  File "/run.py", line 71, in <module>
    run(cmd)
  File "/run.py", line 25, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 127
```

**Comment by justbennet** [comment]
I modified `run.py` to print the contents of `$PATH` and to print the location of `bet` with `which bet`.  Rerunning the docker container, tells me that

```
/usr/lib/fsl/5.0:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
which bet
/usr/lib/fsl/5.0/bet
```

After running the conversion again, it instead prints,

```
/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin/:/usr/local/sbin/:/usr/lib64/qt-3.3/bin:/opt/moab/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/home/bennet/bin
which bet
```

So, that tells me that the `PATH` in the singularity container is the `PATH` from my shell on the machine running the conversion, not the `PATH` defined inside the `example` container.

I start a subshell, export the `PATH` as shown by running the docker container, then reran the conversion command, and still not joy.  I then took a look at `/etc/singularity/init`, and found that path was getting set there.  After a couple of iterations, I discovered that I have to set the `PATH` there explicitly, and after setting it to the `PATH` as shown when running from docker, I make some progress, but still get

```
$ /tmp/singularity/example-2016-09-05-a3ad9bb76289.img /home/bennet/bids_dataset/d005_R1.1.0 /home/bennet/bids_output participant --participant_label 01
    1: You should define 'SliceTiming' for this file. If you don't provide this information slice time correction will not be possible. (code: 13)
        /sub-01/func/sub-01_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-01/func/sub-01_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-01/func/sub-01_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-04/func/sub-04_task-mixedgamblestask_run-01_bold.nii.gz
        ... and 38 more files having this issue (Use --verbose to see them all).

        Summary:                 Available Tasks:          Available Modalities: 
        133 Files, 1.77GB        mixed-gambles task        T1w                   
        16 - Subjects                                      inplaneT2             
        1 - Session                                        bold                  


/usr/lib/fsl/5.0:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
which bet
/usr/lib/fsl/5.0/bet

bet /home/bennet/bids_dataset/d005_R1.1.0/sub-01/anat/sub-01_T1w.nii.gz /home/bennet/bids_output/sub-01_brain.nii.gz
/usr/lib/fsl/5.0/bet: 1: /usr/lib/fsl/5.0/bet: /bin/remove_ext: not found
/usr/lib/fsl/5.0/bet: 1: /usr/lib/fsl/5.0/bet: /bin/remove_ext: not found
/usr/lib/fsl/5.0/bet: 1: /usr/lib/fsl/5.0/bet: /bin/imtest: not found
/usr/lib/fsl/5.0/bet: 154: [: =: unexpected operator
/usr/lib/fsl/5.0/bet: 236: /usr/lib/fsl/5.0/bet: /bin/bet2: not found
```

**Comment by justbennet** [comment]
This appears to be, at least in part, an issue with Singularity.  I will try unistalling the Singularity from the EPEL repo and building it from source.

**Comment by chrisgorgo** [comment]
Which version of singularity are you using? I believe environment variable
set up (which we use in docker2singularity) was introduced in 2.1.

**Comment by justbennet** [comment]
I was using the singularity installed by

singularity-2.0-9.el7.x86_64.rpm

from the EPEL testing repository.  I built a version of singularity from
source, version 2.1.2.

I'll try starting over using that version.

-- bennet

**Comment by justbennet** [comment]
Looks like there was either something wrong with the configuration of the singularity I installed from EPEL, or it may have been too old.  After compiling singularity from source, I recreated things, and I now get The Good Stuff.

```
$ /tmp/singularity/example-2016-09-05-645e068d95b1.img /home/bennet/bids_dataset/d005_R1.1.0 /home/bennet/bids_output participant --participant_label 01
    1: You should define 'SliceTiming' for this file. If you don't provide this information slice time correction will not be possible. (code: 13)
        /sub-01/func/sub-01_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-01/func/sub-01_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-01/func/sub-01_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-02/func/sub-02_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-01_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-02_bold.nii.gz
        /sub-03/func/sub-03_task-mixedgamblestask_run-03_bold.nii.gz
        /sub-04/func/sub-04_task-mixedgamblestask_run-01_bold.nii.gz
        ... and 38 more files having this issue (Use --verbose to see them all).

        Summary:                 Available Tasks:          Available Modalities: 
        133 Files, 1.77GB        mixed-gambles task        T1w                   
        16 - Subjects                                      inplaneT2             
        1 - Session                                        bold                  


/usr/lib/fsl/5.0:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
which bet
/usr/lib/fsl/5.0/bet

bet /home/bennet/bids_dataset/d005_R1.1.0/sub-01/anat/sub-01_T1w.nii.gz /home/bennet/bids_output/sub-01_brain.nii.gz
```

**Comment by justbennet** [comment]
I will close this issue.

**Comment by chrisgorgo** [comment]
@gmkurtzer have a look at this - it seems that EPEL is still hosting singularity 2.0 instead of 2.1

**Comment by gmkurtzer** [comment]
Thank you for the heads up. Yes, we need to find someone to take over EPEL maintenance. I was speaking with the Centos lead (KB) about it last week, he mentioned it is actually pretty easy so I might take that on myself if I don't get another volunteer.

Thanks!

**Comment by justbennet** [comment]
I have some little experience with building .rpms, and I suspect it's not too hard, too.  @gmkurtzer if you want to split duties, I'll be glad to help out.

**Comment by gmkurtzer** [comment]
@justbennet Oh, that would be very cool! I already have SPEC files for Singularity and it builds RPMS directly from the tarball (http://singularity.lbl.gov/#install - Building RPMS from source).

This means that mostly what is needed is just understanding what the EPEL requirements are, making sure that the Singularity SPEC file meets those requirements and then pushing it into EPEL. I have no experience with EPEL aside from being a user, so I can't help much .. yet.

Do you want to check into it and see what is necessary and if you are up for the task?

Thanks!

**Comment by justbennet** [comment]
I have no experience with EPEL except as a consumer yet, either.

It looks like the guidelines are at

https://fedoraproject.org/wiki/EPEL_Package_Maintainers
https://fedoraproject.org/wiki/Join_the_package_collection_maintainers

It looks like Dave Love (loveshack) is the current maintainer.  I'm
wondering if we should write him and ask whether he'd be willing to mentor
the two of us in becoming comaintainers of the singularity package?

loveshack@fedoraproject.org

He says 'comaintainers welcome'.  There are several patches that he
applies, and it might be good to review those, too.

If you want to take this out of this issue, you can write me directly at
bennet [at] umich in the edu domain.

-- bennet

-- bennet

**Comment by gmkurtzer** [comment]
@loveshack did a great job getting the initial work done on the EPEL packaging and can probably fill us in on the current status and/or his long term intentions.

The last time I looked, his patches in the EPEL/Fedora RPMS were mostly cherry picked from upstream or already contributed back, but a more detailed review should be made to see if anything is applicable to the 2.1 or 2.2 releases.

Thanks!

**Comment by loveshack** [comment]
"Gregory M. Kurtzer" notifications@github.com writes:

> @loveshack did a great job getting the initial work done on the EPEL
> packaging and can probably fill us in on the current status and/or his
> long term intentions.

It needs to be raised on fedora-devel and have another go at
fedora-legal, for which I haven't had time.  It looks like a mistake
trying to get it into Fedora, for various reasons.

> The last time I looked, his patches in the EPEL/Fedora RPMS were
> mostly cherry picked from upstream or already contributed back, but a
> more detailed review should be made to see if anything is applicable
> to the 2.1 or 2.2 releases.

There's a load of stuff that's applicable, but a forked version or
mega-patches are probably not acceptable for Fedora.  There's also at
least one unresolved bug that causes fundamental problems with loop
devices for me.
